[project]
name = "media_downloader"
version = "0.1.0"
description = "Android media downloader built with Flet and yt-dlp"
requires-python = ">=3.13,<3.14"
dependencies = [
    "flet==0.86.2",
    "yt-dlp>=2026.8.0",
]

[tool.flet]
product = "Media Downloader"
org = "com.mohammed"
bundle_id = "com.mohammed.mediadownloader"
artifact = "MediaDownloader"
splash_color = "#0f172a"
splash_dark_color = "#0f172a"

[tool.flet.app]
path = "src"
module = "main.py"

[tool.flet.android]
target_sdk_version = 35
target_arch = ["arm64-v8a"]
permissions = [
    "android.permission.INTERNET=true",
    "android.permission.ACCESS_NETWORK_STATE=true",
]
